services:
  frg-db:
    container_name: database
    image: postgres:16
    ports:
      - "127.0.0.1:5555:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 5
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100

    restart: unless-stopped
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

  frg-redis:
    image: redis:8.2.1
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    volumes:
      - ./volumes/redis_limiter_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      sh -c '
        rm -rf /data/* /usr/local/etc/redis/* &&
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on >$REDIS_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  frg-rate-limiter-redis:
    image: redis:8.2.1
    container_name: redis-rate-limiter
    environment:
      - REDIS_PASSWORD=${RATE_LIMIT_PASSWORD}
      - REDIS_USER=${RATE_LIMIT_USER}
      - REDIS_USER_PASSWORD=${RATE_LIMIT_USER_PASSWORD}
    volumes:
      - ./volumes/redisdata:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      sh -c '
        rm -rf /data/* /usr/local/etc/redis/* &&
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $RATE_LIMIT_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on >$RATE_LIMIT_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        echo "user $RATE_LIMIT_USER on >$RATE_LIMIT_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$RATE_LIMIT_PASSWORD", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  frg-api:
    container_name: api
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_ECHO=false
      - APP_DEBUG=false
    ports:
      - "127.0.0.1:8080:8000"
    volumes:
      - ./backend/src:/opt/app/src
    restart: always
    depends_on:
      frg-db:
        condition: service_healthy
      frg-redis:
        condition: service_healthy
      frg-rate-limiter-redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

  frg-website:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: website
    ports:
      - "127.0.0.1:3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_TELEGRAM_GROUP_URL=${VITE_TELEGRAM_GROUP_URL:-''}
      - VITE_TELEGRAM_BOT_URL=${VITE_TELEGRAM_BOT_URL:-''}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
